/**
 * generated by Xtext
 */
package yang.manager.validation;

import yang.manager.validation.AbstractYangValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class YangValidator extends AbstractYangValidator {
}
