/*
 * generated by Xtext
 */
package yang.manager.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.documentation.IEObjectDocumentationProvider;
//import org.eclipse.xtext.ui.editor.contentassist.XtextContentAssistProcessor;//this needs to be enabled for content assist
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;

//import com.google.inject.Binder;//used in content assist

/**
 * Use this class to register components to be used within the IDE.
 */
public class YangUiModule extends yang.manager.ui.AbstractYangUiModule {
	public YangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
    
	public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
        return yangHoverProvider.class;
    }
 
    public Class<? extends IEObjectDocumentationProvider> bindIEObjectDocumentationProviderr() {
        return yangDocumentationProvider.class;
    }
    
    
    /*		//This is the automatic content assistance. Currently disabled
    @Override
    public void configure(Binder binder) {
        super.configure(binder);
    binder.bind(String.class)
    .annotatedWith(com.google.inject.name.Names.named((XtextContentAssistProcessor.COMPLETION_AUTO_ACTIVATION_CHARS)))
.toInstance("d");// choose the characters that will be automatically checked for assistance. Currently only "d" would be checked
    }*/
}