/*
 * generated by Xtext
 */
package yang.manager;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class YangRuntimeModule extends yang.manager.AbstractYangRuntimeModule {

}
