/*
 * generated by Xtext
 */
package yang.manager.ui.contentassist

import yang.manager.ui.contentassist.AbstractYangProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class YangProposalProvider extends AbstractYangProposalProvider {
	}
