/*
* generated by Xtext
*/
package yang.manager;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class YangUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return yang.manager.ui.internal.YangActivator.getInstance().getInjector("yang.manager.Yang");
	}
	
}
